spring:
  application:
    name: ibmec-mall
  
  # Configuração do Azure SQL Database
  datasource:
    url: ${AZURE_SQL_URL}
    username: ${AZURE_SQL_USERNAME}
    password: ${AZURE_SQL_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  
  # Configuração do Azure Cosmos DB
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_ENDPOINT}
        key: ${AZURE_COSMOS_KEY}
        database: ibmec-mall-db
        container: produtos
      eventhubs:
        connection-string: ${AZURE_EVENTHUB_CONNECTION_STRING}
        event-hub-name: vendas-events

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method 